sudo: false
language: cpp
compiler: clang
branches:
    except:
        - gh-pages
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
        packages:
            - g++-4.9
            - clang-3.7
            - doxygen
            - lcov
before_script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - git clone --depth 1 https://github.com/urho3d/emscripten-sdk.git && emscripten-sdk/emsdk activate --build=Release sdk-master-64bit && source emscripten-sdk/emsdk_env.sh
    - cat ~/.emscripten
    - emcc -v
    - g++ -v
    - clang++ -v
    - node -v
script:
    - npm install
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - clang++ -v
    - make native
    - source emscripten-sdk/emsdk_env.sh
    - clang++ -v
    - make js
    - make testjs
    - make testnative
after_success:
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - clang++ -v
    - make docs
